In [2]:
import fiscalpy as fp
import pandas as pd
from fiscalpy import limpieza_ingresos_territoriales
from fiscalpy import columnas_ingresos_territoriales
from fiscalpy import limpieza_gastos_territoriales

ModuleNotFoundError: No module named 'utils'

In [8]:
df = pd.read_excel("C:/Users/SebasM/OneDrive/Documentos/try/ejec_gast_25.xlsb")

In [9]:
df

,Año Vigencia,Periodo,Cadena Periodo,Código DANE,Código FUT,Entidad,Tipo de Entidad,Departamento,Region,SubRegion,...,BPIN,Código Situacion Fondos,Situacion Fondos,Código Política Pública,Política Pública,Código Tercero,Tercero,Compromisos,Obligaciones,Pagos
0,2025,Anual (Enero - Diciembre) ...,11212,5000,110505000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,...,...,,,...,,...,...,...,3116989215251,2664210538067,2563198790347
1,2025,Anual (Enero - Diciembre) ...,11212,5000,110505000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,...,...,,,...,,...,...,...,3204095229,3204095229,3204095229
2,2025,Anual (Enero - Diciembre) ...,11212,5000,110505000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,...,...,,,...,,...,...,...,22716948233,22555845038,22405185231
3,2025,Anual (Enero - Diciembre) ...,11212,5000,110505000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,...,...,,,...,,...,...,...,188392404990,188392404990,188392404990
4,2025,Anual (Enero - Diciembre) ...,11212,5000,110505000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,...,...,,,...,,...,...,...,3019866058034,2986826367323,2977429179229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
773410,2025,Anual (Enero - Diciembre) ...,11212,27493,923273478,Nuevo Belén de Bajirá ...,Municipio ...,Chocó ...,Pacífica ...,NaN,...,,,...,,...,...,...,1220182317,1220182317,1179744489
773411,2025,Anual (Enero - Diciembre) ...,11212,27493,923273478,Nuevo Belén de Bajirá ...,Municipio ...,Chocó ...,Pacífica ...,NaN,...,,,...,,...,...,...,1220182317,1220182317,1179744489
773412,2025,Anual (Enero - Diciembre) ...,11212,27493,923273478,Nuevo Belén de Bajirá ...,Municipio ...,Chocó ...,Pacífica ...,NaN,...,1321006,C,CON SITUACION DE FONDOS ...,0,NO APLICA ...,923272412 ...,"MINISTERIO DE VIVIENDA, CIUDAD Y TERRITORIO ...",1220182317,1220182317,1179744489
773413,2025,Anual (Enero - Diciembre) ...,11212,27493,923273478,Nuevo Belén de Bajirá ...,Municipio ...,Chocó ...,Pacífica ...,NaN,...,,,...,,...,...,...,2018446,2018446,2018446
773414,2025,Anual (Enero - Diciembre) ...,11212,27493,923273478,Nuevo Belén de Bajirá ...,Municipio ...,Chocó ...,Pacífica ...,NaN,...,202500000015433,C,CON SITUACION DE FONDOS ...,0,NO APLICA ...,1 ...,NO APLICA ...,2018446,2018446,2018446

In [10]:
norm_data = limpieza_gastos_territoriales(df, tipo='ejecucion')

c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'GASTOS' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'FUNCIONAMIENTO' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'GASTOS DE PERSONAL' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'PLANTA DE PERSONAL PERMANENTE' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'FACTORES CONSTITUTIVOS DE SALARIO' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'FACTORES SALARIALES COMUNES' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'SUELDO BASICO' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'PRIMA DE NAVIDAD' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'MUEBLES DEL TIPO UTILIZADO EN LA OFICINA' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'PAQUETES DE SOFTWARE' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:307: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sons[['col_1', 'col_2', 'col_3', 'col_4', 'col_5', 'col_6',
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:310: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sons.drop(columns=['split', 'lists_tuple', 'example'], inplace=True)

In [11]:
norm_data

,Año Vigencia,Código DANE,Entidad,Tipo de Entidad,Departamento,Region,Código Concepto,Concepto,Código Vigencia del Gasto,Vigencia del Gasto,...,col_4,col_5,col_6,col_7,col_8,col_9,col_10,Compromisos,Obligaciones,Pagos
0,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,2.1.1.01.01.001.01,SUELDO BASICO,1,VIGENCIA ACTUAL ...,...,PLANTA DE PERSONAL PERMANENTE,FACTORES CONSTITUTIVOS DE SALARIO,FACTORES SALARIALES COMUNES,SUELDO BASICO,SUELDO BASICO,SUELDO BASICO,SUELDO BASICO,92902846242,92902846242,92902846242
1,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,2.1.1.01.01.001.01,SUELDO BASICO,1,VIGENCIA ACTUAL ...,...,PLANTA DE PERSONAL PERMANENTE,FACTORES CONSTITUTIVOS DE SALARIO,FACTORES SALARIALES COMUNES,SUELDO BASICO,SUELDO BASICO,SUELDO BASICO,SUELDO BASICO,26321664559,26321664559,26320951731
2,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,2.1.1.01.01.001.01,SUELDO BASICO,1,VIGENCIA ACTUAL ...,...,PLANTA DE PERSONAL PERMANENTE,FACTORES CONSTITUTIVOS DE SALARIO,FACTORES SALARIALES COMUNES,SUELDO BASICO,SUELDO BASICO,SUELDO BASICO,SUELDO BASICO,784038645,784038645,784038645
3,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,2.1.1.01.01.001.01,SUELDO BASICO,1,VIGENCIA ACTUAL ...,...,PLANTA DE PERSONAL PERMANENTE,FACTORES CONSTITUTIVOS DE SALARIO,FACTORES SALARIALES COMUNES,SUELDO BASICO,SUELDO BASICO,SUELDO BASICO,SUELDO BASICO,8351964880,8351964880,8351964880
4,2025,5000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,2.1.1.01.01.001.01,SUELDO BASICO,1,VIGENCIA ACTUAL ...,...,PLANTA DE PERSONAL PERMANENTE,FACTORES CONSTITUTIVOS DE SALARIO,FACTORES SALARIALES COMUNES,SUELDO BASICO,SUELDO BASICO,SUELDO BASICO,SUELDO BASICO,11862635003,11862635003,11862635003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171679,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,Llano ...,2.3.2.02.02.009,"SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSON...",2,RESERVAS ...,...,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,"SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSON...","SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSON...","SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSON...","SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSON...","SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSON...",931413072,927413072,927413072
171680,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,Llano ...,2.3.3.01.02.004.01,SUBSIDIOS DE ACUEDUCTO,1,VIGENCIA ACTUAL ...,...,SUBVENCIONES,A EMPRESAS PUBLICAS NO FINANCIERAS,SUBVENCIONES PARA SERVICIOS PUBLICOS DOMICILIA...,SUBSIDIOS DE ACUEDUCTO,SUBSIDIOS DE ACUEDUCTO,SUBSIDIOS DE ACUEDUCTO,SUBSIDIOS DE ACUEDUCTO,262641326,262641326,262641326
171681,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,Llano ...,2.3.3.01.02.004.02,SUBSIDIOS DE ALCANTARILLADO,1,VIGENCIA ACTUAL ...,...,SUBVENCIONES,A EMPRESAS PUBLICAS NO FINANCIERAS,SUBVENCIONES PARA SERVICIOS PUBLICOS DOMICILIA...,SUBSIDIOS DE ALCANTARILLADO,SUBSIDIOS DE ALCANTARILLADO,SUBSIDIOS DE ALCANTARILLADO,SUBSIDIOS DE ALCANTARILLADO,43711478,43711478,43711478
171682,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,Llano ...,2.3.3.01.02.004.03,SUBSIDIOS DE ASEO,1,VIGENCIA ACTUAL ...,...,SUBVENCIONES,A EMPRESAS PUBLICAS NO FINANCIERAS,SUBVENCIONES PARA SERVICIOS PUBLICOS DOMICILIA...,SUBSIDIOS DE ASEO,SUBSIDIOS DE ASEO,SUBSIDIOS DE ASEO,SUBSIDIOS DE ASEO,213141209,213141209,213141209
171683,2025,99773,Cumaribo ...,Municipio ...,Vichada ...,Llano ...,2.3.7.05.03,"PAGO DE DEFICIT FISCAL, DE PASIVO LABORAL Y PR...",1,VIGENCIA ACTUAL ...,...,PROGRAMAS DE SANEAMIENTO FISCAL Y FINANCIERO,"PAGO DE DEFICIT FISCAL, DE PASIVO LABORAL Y PR...","PAGO DE DEFICIT FISCAL, DE PASIVO LABORAL Y PR...","PAGO DE DEFICIT FISCAL, DE PASIVO LABORAL Y PR...","PAGO DE DEFICIT FISCAL, DE PASIVO LABORAL Y PR...","PAGO DE DEFICIT FISCAL, DE PASIVO LABORAL Y PR...","PAGO DE DEFICIT FISCAL, DE PASIVO LABORAL Y PR...",2879477082,2879477082,2879477082

In [14]:
norm_data.to_excel('eje_gast_clean25.xlsx', index = False)

Exception ignored in: <function ZipFile.__del__ at 0x000001BCD4D44AE0>
Traceback (most recent call last):
  File "c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\zipfile\__init__.py", line 1988, in __del__
    self.close()
  File "c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\zipfile\__init__.py", line 2005, in close
    self.fp.seek(self.start_dir)
ValueError: seek of closed file

In [15]:
df1 = pd.read_excel("C:/Users/SebasM/OneDrive/Documentos/try/prog_gast_25.xlsb")

In [19]:
df1

,Año Vigencia,Periodo,Cadena Periodo,Código DANE,Código FUT,Entidad,Tipo de Entidad,Departamento,Region,SubRegion,...,Concepto,Código Vigencia del Gasto,Vigencia del Gasto,Código Sección Presupuestal,Sección Presupuestal,Código Programa MGA,Programa MGA,BPIN,Apropiación Inicial,Apropiación Definitiva
0,2025,Anual (Enero - Diciembre) ...,11212,5000,110505000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,...,...,GASTOS ...,1,VIGENCIA ACTUAL ...,21.0,ENTIDADES TERRITORIALES - SALUD ...,...,...,...,947227227039,1345537897241
1,2025,Anual (Enero - Diciembre) ...,11212,5000,110505000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,...,...,GASTOS ...,1,VIGENCIA ACTUAL ...,16.0,ENTIDADES TERRITORIALES - ADMINISTRACION CENTR...,...,...,...,2510154281822,3348567430841
2,2025,Anual (Enero - Diciembre) ...,11212,5000,110505000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,...,...,GASTOS ...,1,VIGENCIA ACTUAL ...,17.0,ENTIDADES TERRITORIALES - CONTRALORIA ...,...,...,...,47993051530,51978965244
3,2025,Anual (Enero - Diciembre) ...,11212,5000,110505000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,...,...,GASTOS ...,1,VIGENCIA ACTUAL ...,22.0,ENTIDADES TERRITORIALES - EDUCACION ...,...,...,...,2185802265794,3132137341399
4,2025,Anual (Enero - Diciembre) ...,11212,5000,110505000,Antioquia ...,Departamento ...,Antioquia ...,Eje cafetero ...,...,...,GASTOS ...,1,VIGENCIA ACTUAL ...,19.0,ENTIDADES TERRITORIALES - ASAMBLEA ...,...,...,...,24631435367,25206936193
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348515,2025,Anual (Enero - Diciembre) ...,11212,99773,217399773,Cumaribo ...,Municipio ...,Vichada ...,Llano ...,Subregión Orinoquia ...,...,CONSOLIDACION ...,2,RESERVAS ...,16.0,ENTIDADES TERRITORIALES - ADMINISTRACION CENTR...,4101 ...,"Atencion, asistencia y reparacion integral a ...",2024997730041 ...,13814000,13814000
348516,2025,Anual (Enero - Diciembre) ...,11212,99773,217399773,Cumaribo ...,Municipio ...,Vichada ...,Llano ...,Subregión Orinoquia ...,...,CONSOLIDACION ...,2,RESERVAS ...,16.0,ENTIDADES TERRITORIALES - ADMINISTRACION CENTR...,1903 ...,"Inspeccion, vigilancia y control ...",2024997730032 ...,143194000,143194000
348517,2025,Anual (Enero - Diciembre) ...,11212,99773,217399773,Cumaribo ...,Municipio ...,Vichada ...,Llano ...,Subregión Orinoquia ...,...,CONSOLIDACION ...,2,RESERVAS ...,16.0,ENTIDADES TERRITORIALES - ADMINISTRACION CENTR...,1905 ...,Salud Publica ...,2024997730011 ...,464800000,464800000
348518,2025,Anual (Enero - Diciembre) ...,11212,99773,217399773,Cumaribo ...,Municipio ...,Vichada ...,Llano ...,Subregión Orinoquia ...,...,CONSOLIDACION ...,2,RESERVAS ...,16.0,ENTIDADES TERRITORIALES - ADMINISTRACION CENTR...,4101 ...,"Atencion, asistencia y reparacion integral a ...",2024997730038 ...,1900000,1900000
348519,2025,Anual (Enero - Diciembre) ...,11212,99773,217399773,Cumaribo ...,Municipio ...,Vichada ...,Llano ...,Subregión Orinoquia ...,...,CONSOLIDACION ...,2,RESERVAS ...,16.0,ENTIDADES TERRITORIALES - ADMINISTRACION CENTR...,4599 ...,Fortalecimiento a la gestion y direccion de la...,2024997730037 ...,5280000,5280000

In [20]:
norm_data1 = limpieza_gastos_territoriales(df1, tipo='programacion')

c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'GASTOS' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'FUNCIONAMIENTO' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'GASTOS DE PERSONAL' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'PLANTA DE PERSONAL PERMANENTE' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'FACTORES CONSTITUTIVOS DE SALARIO' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'FACTORES SALARIALES COMUNES' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'SUELDO BASICO' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'PRIMA DE NAVIDAD' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'MUEBLES DEL TIPO UTILIZADO EN LA OFICINA' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:282: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'PAQUETES DE SOFTWARE' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df2.loc[idx, f'col_{i}'] = dictio_con['.'.join(split[:i])]
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:307: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sons[['col_1', 'col_2', 'col_3', 'col_4', 'col_5', 'col_6',
c:\Users\SebasM\AppData\Local\Programs\Python\Python313\Lib\site-packages\fiscalpy\limpieza.py:310: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sons.drop(columns=['split', 'lists_tuple', 'example'], inplace=True)

KeyError: "Columns not found: 'Apropiaciones'"